### ISSUE TITLE
Update Interval not being obeyed

### ISSUE THREAD

**Issue by ardsar01** [ad-ha/mg-saic-ha#127]
### Home Assistant Version

2025.2.5

### MG/SAIC Integration Version

0.9.4

### Installation Method

HACS

### Did you check for existing issues?

- [x] Yes, I have checked for existing issues
- [ ] No, I have not checked for existing issues

### Did you enable debug logging before and are ready to post logs?

- [x] Yes, I have enabled debug logging
- [ ] No, I have not enabled debug logging

### Describe the Issue

I have set the update time interval to 240 mins, however it still seems to be updating every 60 minis. Re-loading the integration has not helped.

Also, is there a description somewhere of what all the update values do?

### Logs

```yaml

```

**Comment by ad-ha** [comment]
Can you try to manually edit UPDATE_INTERVAL in `/custom_components/mg_saic/const.py` and change to this `UPDATE_INTERVAL = timedelta(minutes=240)` restart integration and check if it works fine.

The configuration should be working fine, at least in my case it does, but let's see if this way it fits better.



> Also, is there a description somewhere of what all the update values do?

What do you mean by this?

**Comment by ardsar01** [comment]
I have made this change, and the update time has changed to 4 hours. However,  just reloading the integration did not seem to work. After a reboot, the changes were applied!

I was not clear on what some of the update intervals are for - e.g.

Heated Seats "long interval"
Charging "long interval"

What is meant by long interval?

Grace period update interval?

**Comment by ardsar01** [comment]
Over the weekend i changed charging update interval from 10 to 15 mins. This worked. However the main update interval at the top of the list still does not. Maybe that helps with the debug?

**Comment by simonsupakru** [comment]
Hello, after changing the values manually in "/custom_components/mg_saic/const.py", 

UPDATE_INTERVAL => OK 
UPDATE_INTERVAL_CHARGING => OK
UPDATE_INTERVAL_POWERED => Seems to be OK 
UPDATE_INTERVAL_AFTER_SHUTDOWN => NOK (I don't have any update after shutdown)

Other problem, it seems that all the entities are not updated at the same time. For example (screenshot at the same time) !

![Image](https://github.com/user-attachments/assets/353a1e77-2022-4fe8-9429-9e56968d9d6f)

 
![Image](https://github.com/user-attachments/assets/15ee82bc-aaae-4f13-bf86-2df8e19b0a21)

![Image](https://github.com/user-attachments/assets/61436fa4-c7dc-4296-a6ae-811480a82d7b)

![Image](https://github.com/user-attachments/assets/0690b529-062a-4057-8c70-862787437bc1)

**Comment by ad-ha** [comment]
It all seems to be alright. On those graphs, if the values don't change you get the time marker from the last change. So the Front Left has the same pressure for the last 3 hours, whilst Front Right has a slight increase to 2.72 bar.

The shutdown update only happens if the vehicle is detected on and after is detected off (if you turn on and off the vehicle without the integration getting the change on the given intervals, as we do not get push notifications from the car, nothing happens)... it should recheck after the update time defined, but is a regular update. Nothing out of the ordinary.

**Comment by lordsnipe1** [comment]
I seem to be having the same issue. I tried changing the "Update Interval" in the options menu, which had no effect (even after restarting HA). Editing the const.py directly and restarting HA worked.
